// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents the aggregation level and interval for pricing of a single SKU.
public struct AggregationInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var aggregationLevel: AggregationInfo.AggregationLevel = AggregationInfo.AggregationLevel()

  public var aggregationInterval: AggregationInfo.AggregationInterval =
    AggregationInfo.AggregationInterval()

  /// The number of intervals to aggregate over.
  /// Example: If aggregation_level is "DAILY" and aggregation_count is 14,
  /// aggregation will be over 14 days.
  public var aggregationCount: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AggregationInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AggregationInfo().with { $0.aggregationLevel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let aggregationLevel = CodingKeys(stringValue: "aggregationLevel")
    static let aggregationInterval = CodingKeys(stringValue: "aggregationInterval")
    static let aggregationCount = CodingKeys(stringValue: "aggregationCount")

    static let _knownKeys: Set<Swift.String> = [
      "aggregationLevel",
      "aggregationInterval",
      "aggregationCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      AggregationInfo.AggregationLevel.self, forKey: .aggregationLevel)
    {
      self.aggregationLevel = value
    }
    if let value = try container.decodeIfPresent(
      AggregationInfo.AggregationInterval.self, forKey: .aggregationInterval)
    {
      self.aggregationInterval = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .aggregationCount) {
      self.aggregationCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.aggregationLevel, forKey: .aggregationLevel)
    try container.encode(self.aggregationInterval, forKey: .aggregationInterval)
    try container.encode(self.aggregationCount, forKey: .aggregationCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The level at which usage is aggregated to compute cost.
  /// Example: "ACCOUNT" aggregation level indicates that usage for tiered
  /// pricing is aggregated across all projects in a single account.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AggregationLevel: Codable, Equatable, Hashable, Sendable {
    case unspecified
    case account
    case project
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .account: return 1
      case .project: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AGGREGATION_LEVEL_UNSPECIFIED"
      case .account: return "ACCOUNT"
      case .project: return "PROJECT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AggregationLevel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AGGREGATION_LEVEL_UNSPECIFIED": self = .unspecified
      case "ACCOUNT": self = .account
      case "PROJECT": self = .project
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AggregationLevel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .account
      case 2: self = .project
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AGGREGATION_LEVEL_UNSPECIFIED")
      case .account: return try container.encode("ACCOUNT")
      case .project: return try container.encode("PROJECT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The interval at which usage is aggregated to compute cost.
  /// Example: "MONTHLY" aggregation interval indicates that usage for tiered
  /// pricing is aggregated every month.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AggregationInterval: Codable, Equatable, Hashable, Sendable {
    case unspecified
    case daily
    case monthly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .daily: return 1
      case .monthly: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AGGREGATION_INTERVAL_UNSPECIFIED"
      case .daily: return "DAILY"
      case .monthly: return "MONTHLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AggregationInterval/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AGGREGATION_INTERVAL_UNSPECIFIED": self = .unspecified
      case "DAILY": self = .daily
      case "MONTHLY": self = .monthly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AggregationInterval/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .daily
      case 2: self = .monthly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("AGGREGATION_INTERVAL_UNSPECIFIED")
      case .daily: return try container.encode("DAILY")
      case .monthly: return try container.encode("MONTHLY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.AggregationInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
