// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A billing account in the
/// [Google Cloud Console](https://console.cloud.google.com/). You can assign a
/// billing account to one or more projects.
public struct BillingAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the billing account. The resource name
  /// has the form `billingAccounts/{billing_account_id}`. For example,
  /// `billingAccounts/012345-567890-ABCDEF` would be the resource name for
  /// billing account `012345-567890-ABCDEF`.
  public var name: Swift.String = Swift.String()

  /// Output only. True if the billing account is open, and will therefore be
  /// charged for any usage on associated projects. False if the billing account
  /// is closed, and therefore projects associated with it are unable to use paid
  /// services.
  public var `open`: Swift.Bool = Swift.Bool()

  /// The display name given to the billing account, such as `My Billing
  /// Account`. This name is displayed in the Google Cloud Console.
  public var displayName: Swift.String = Swift.String()

  /// If this account is a
  /// [subaccount](https://cloud.google.com/billing/docs/concepts), then this
  /// will be the resource name of the parent billing account that it is being
  /// resold through.
  /// Otherwise this will be empty.
  public var masterBillingAccount: Swift.String = Swift.String()

  /// Output only. The billing account's parent resource identifier.
  /// Use the `MoveBillingAccount` method to update the account's parent resource
  /// if it is a organization.
  /// Format:
  ///   - `organizations/{organization_id}`, for example,
  ///     `organizations/12345678`
  ///   - `billingAccounts/{billing_account_id}`, for example,
  ///     `billingAccounts/012345-567890-ABCDEF`
  public var parent: Swift.String = Swift.String()

  /// Optional. The currency in which the billing account is billed and charged,
  /// represented as an ISO 4217 code such as `USD`.
  ///
  /// Billing account currency is determined at the time of billing account
  /// creation and cannot be updated subsequently, so this field should not be
  /// set on update requests. In addition, a subaccount always matches the
  /// currency of its parent billing account, so this field should not be set on
  /// subaccount creation requests. Clients can read this field to determine the
  /// currency of an existing billing account.
  public var currencyCode: Swift.String = Swift.String()

  /// Initialize a new instance of `BillingAccount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BillingAccount().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case `open` = "open"
    case displayName = "displayName"
    case masterBillingAccount = "masterBillingAccount"
    case parent = "parent"
    case currencyCode = "currencyCode"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.`open` = try container.decode(Swift.Bool.self, forKey: .`open`)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.masterBillingAccount = try container.decode(
      Swift.String.self, forKey: .masterBillingAccount)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.currencyCode = try container.decode(Swift.String.self, forKey: .currencyCode)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.`open`, forKey: .`open`)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.masterBillingAccount, forKey: .masterBillingAccount)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.currencyCode, forKey: .currencyCode)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.BillingAccount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
