// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents the category hierarchy of a SKU.
public struct Category: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The display name of the service this SKU belongs to.
  public var serviceDisplayName: Swift.String = Swift.String()

  /// The type of product the SKU refers to.
  /// Example: "Compute", "Storage", "Network", "ApplicationServices" etc.
  public var resourceFamily: Swift.String = Swift.String()

  /// A group classification for related SKUs.
  /// Example: "RAM", "GPU", "Prediction", "Ops", "GoogleEgress" etc.
  public var resourceGroup: Swift.String = Swift.String()

  /// Represents how the SKU is consumed.
  /// Example: "OnDemand", "Preemptible", "Commit1Mo", "Commit1Yr" etc.
  public var usageType: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Category`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Category().with { $0.serviceDisplayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serviceDisplayName = CodingKeys(stringValue: "serviceDisplayName")
    static let resourceFamily = CodingKeys(stringValue: "resourceFamily")
    static let resourceGroup = CodingKeys(stringValue: "resourceGroup")
    static let usageType = CodingKeys(stringValue: "usageType")

    static let _knownKeys: Set<Swift.String> = [
      "serviceDisplayName",
      "resourceFamily",
      "resourceGroup",
      "usageType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceDisplayName) {
      self.serviceDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceFamily) {
      self.resourceFamily = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceGroup) {
      self.resourceGroup = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .usageType) {
      self.usageType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.serviceDisplayName, forKey: .serviceDisplayName)
    try container.encode(self.resourceFamily, forKey: .resourceFamily)
    try container.encode(self.resourceGroup, forKey: .resourceGroup)
    try container.encode(self.usageType, forKey: .usageType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.Category"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
