// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudCatalogLogging: CloudCatalogStub {
    let inner: any CloudCatalogStub
    let logger: Logger

    public init(_ inner: any CloudCatalogStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudBillingV1"
      logger[metadataKey: "gcp.client.service"] = "cloudbilling"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudCatalog"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServices",
        action: {
          (r: ListServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingV1.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func listSkus(
      request: ListSkusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.ListSkusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSkus",
        action: {
          (r: ListSkusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingV1.ListSkusResponse
          in
          return try await self.inner.listSkus(request: r, options: o)
        })
    }
  }
}
