// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleGax

/// Retrieves the Google Cloud Console billing accounts and associates them with
/// projects.
///
/// @Snippet(path: "CloudBillingQuickstart")
public final class CloudBillingClient: Clients.CloudBillingProtocol, Sendable {
  let inner: any Clients.CloudBillingStub

  /// Creates a new `CloudBillingClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudBillingStub = try Clients.CloudBillingTransport(options)
    inner = Clients.CloudBillingRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudBillingLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets information about a billing account. The current authenticated user
  /// must be a [viewer of the billing
  /// account](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_GetBillingAccount")
  public func getBillingAccount(
    request: GetBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    try await self.inner.getBillingAccount(request: request, options: options)
  }

  /// Lists the billing accounts that the current authenticated user has
  /// permission to
  /// [view](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_ListBillingAccounts")
  public func listBillingAccounts(
    request: ListBillingAccountsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ListBillingAccountsResponse {
    try await self.inner.listBillingAccounts(request: request, options: options)
  }

  /// Updates a billing account's fields.
  /// Currently the only field that can be edited is `display_name`.
  /// The current authenticated user must have the `billing.accounts.update`
  /// IAM permission, which is typically given to the
  /// [administrator](https://cloud.google.com/billing/docs/how-to/billing-access)
  /// of the billing account.
  ///
  /// @Snippet(path: "CloudBilling_UpdateBillingAccount")
  public func updateBillingAccount(
    request: UpdateBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    try await self.inner.updateBillingAccount(request: request, options: options)
  }

  /// This method creates [billing
  /// subaccounts](https://cloud.google.com/billing/docs/concepts#subaccounts).
  ///
  /// Google Cloud resellers should use the
  /// Channel Services APIs,
  /// [accounts.customers.create](https://cloud.google.com/channel/docs/reference/rest/v1/accounts.customers/create)
  /// and
  /// [accounts.customers.entitlements.create](https://cloud.google.com/channel/docs/reference/rest/v1/accounts.customers.entitlements/create).
  ///
  /// When creating a subaccount, the current authenticated user must have the
  /// `billing.accounts.update` IAM permission on the parent account, which is
  /// typically given to billing account
  /// [administrators](https://cloud.google.com/billing/docs/how-to/billing-access).
  /// This method will return an error if the parent account has not been
  /// provisioned for subaccounts.
  ///
  /// @Snippet(path: "CloudBilling_CreateBillingAccount")
  public func createBillingAccount(
    request: CreateBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    try await self.inner.createBillingAccount(request: request, options: options)
  }

  /// Lists the projects associated with a billing account. The current
  /// authenticated user must have the `billing.resourceAssociations.list` IAM
  /// permission, which is often given to billing account
  /// [viewers](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_ListProjectBillingInfo")
  public func listProjectBillingInfo(
    request: ListProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ListProjectBillingInfoResponse {
    try await self.inner.listProjectBillingInfo(request: request, options: options)
  }

  /// Gets the billing information for a project. The current authenticated user
  /// must have the `resourcemanager.projects.get` permission for the project,
  /// which can be granted by assigning the [Project
  /// Viewer](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles)
  /// role.
  ///
  /// @Snippet(path: "CloudBilling_GetProjectBillingInfo")
  public func getProjectBillingInfo(
    request: GetProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo {
    try await self.inner.getProjectBillingInfo(request: request, options: options)
  }

  /// Sets or updates the billing account associated with a project. You specify
  /// the new billing account by setting the `billing_account_name` in the
  /// `ProjectBillingInfo` resource to the resource name of a billing account.
  /// Associating a project with an open billing account enables billing on the
  /// project and allows charges for resource usage. If the project already had a
  /// billing account, this method changes the billing account used for resource
  /// usage charges.
  ///
  /// *Note:* Incurred charges that have not yet been reported in the transaction
  /// history of the Google Cloud Console might be billed to the new billing
  /// account, even if the charge occurred before the new billing account was
  /// assigned to the project.
  ///
  /// The current authenticated user must have ownership privileges for both
  /// the
  /// [project](https://cloud.google.com/docs/permissions-overview#h.bgs0oxofvnoo
  /// ) and the [billing
  /// account](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// You can disable billing on the project by setting the
  /// `billing_account_name` field to empty. This action disassociates the
  /// current billing account from the project. Any billable activity of your
  /// in-use services will stop, and your application could stop functioning as
  /// expected. Any unbilled charges to date will be billed to the previously
  /// associated account. The current authenticated user must be either an owner
  /// of the project or an owner of the billing account for the project.
  ///
  /// Note that associating a project with a *closed* billing account will have
  /// much the same effect as disabling billing on the project: any paid
  /// resources used by the project will be shut down. Thus, unless you wish to
  /// disable billing, you should always call this method with the name of an
  /// *open* billing account.
  ///
  /// @Snippet(path: "CloudBilling_UpdateProjectBillingInfo")
  public func updateProjectBillingInfo(
    request: UpdateProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo {
    try await self.inner.updateProjectBillingInfo(request: request, options: options)
  }

  /// Gets the access control policy for a billing account.
  /// The caller must have the `billing.accounts.getIamPolicy` permission on the
  /// account, which is often given to billing account
  /// [viewers](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Sets the access control policy for a billing account. Replaces any existing
  /// policy.
  /// The caller must have the `billing.accounts.setIamPolicy` permission on the
  /// account, which is often given to billing account
  /// [administrators](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Tests the access control policy for a billing account. This method takes
  /// the resource and a set of permissions as input and returns the subset of
  /// the input permissions that the caller is allowed for that resource.
  ///
  /// @Snippet(path: "CloudBilling_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Changes which parent organization a billing account belongs to.
  ///
  /// @Snippet(path: "CloudBilling_MoveBillingAccount")
  public func moveBillingAccount(
    request: MoveBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    try await self.inner.moveBillingAccount(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudBillingClient`.
  ///
  /// To mock `CloudBillingClient` change your functions to receive
  /// `some CloudBillingProtocol` or `any CloudBillingProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudBillingProtocol: Sendable {
    /// See `CloudBillingClient.getBillingAccount`.
    func getBillingAccount(
      request: GetBillingAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.BillingAccount

    /// See `CloudBillingClient.listBillingAccounts`.
    func listBillingAccounts(
      request: ListBillingAccountsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.ListBillingAccountsResponse

    /// See `CloudBillingClient.updateBillingAccount`.
    func updateBillingAccount(
      request: UpdateBillingAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.BillingAccount

    /// See `CloudBillingClient.createBillingAccount`.
    func createBillingAccount(
      request: CreateBillingAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.BillingAccount

    /// See `CloudBillingClient.listProjectBillingInfo`.
    func listProjectBillingInfo(
      request: ListProjectBillingInfoRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.ListProjectBillingInfoResponse

    /// See `CloudBillingClient.getProjectBillingInfo`.
    func getProjectBillingInfo(
      request: GetProjectBillingInfoRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo

    /// See `CloudBillingClient.updateProjectBillingInfo`.
    func updateProjectBillingInfo(
      request: UpdateProjectBillingInfoRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo

    /// See `CloudBillingClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `CloudBillingClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `CloudBillingClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `CloudBillingClient.moveBillingAccount`.
    func moveBillingAccount(
      request: MoveBillingAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBillingV1.BillingAccount
  }
}

// Default implementations
extension Clients.CloudBillingProtocol {
  public func getBillingAccount(request: GetBillingAccountRequest) async throws
    -> GoogleCloudBillingV1.BillingAccount
  {
    try await self.getBillingAccount(request: request, options: .init())
  }

  public func getBillingAccount(
    request: GetBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBillingAccount(
    name: Swift.String,
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    let request = GetBillingAccountRequest().with {
      $0.name = name
    }
    return try await self.getBillingAccount(request: request)
  }

  public func listBillingAccounts(request: ListBillingAccountsRequest) async throws
    -> GoogleCloudBillingV1.ListBillingAccountsResponse
  {
    try await self.listBillingAccounts(request: request, options: .init())
  }

  public func listBillingAccounts(
    request: ListBillingAccountsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ListBillingAccountsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBillingAccounts(
    byItem: ListBillingAccountsRequest
  ) -> any AsyncSequence<BillingAccount, Swift.Error> {
    self.listBillingAccounts(byItem: byItem, options: .init())
  }

  /// Lists the billing accounts that the current authenticated user has
  /// permission to
  /// [view](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_ListBillingAccounts")
  public func listBillingAccounts(
    byItem: ListBillingAccountsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<BillingAccount, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBillingV1.ListBillingAccountsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBillingAccounts(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBillingAccounts(
    parent: Swift.String,
  ) -> any AsyncSequence<BillingAccount, Swift.Error> {
    let request = ListBillingAccountsRequest().with {
      $0.parent = parent
    }
    return self.listBillingAccounts(byItem: request)
  }

  public func updateBillingAccount(request: UpdateBillingAccountRequest) async throws
    -> GoogleCloudBillingV1.BillingAccount
  {
    try await self.updateBillingAccount(request: request, options: .init())
  }

  public func updateBillingAccount(
    request: UpdateBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateBillingAccount(
    name: Swift.String,
    account: BillingAccount?,
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    let request = UpdateBillingAccountRequest().with {
      $0.name = name
      $0.account = account
    }
    return try await self.updateBillingAccount(request: request)
  }

  public func createBillingAccount(request: CreateBillingAccountRequest) async throws
    -> GoogleCloudBillingV1.BillingAccount
  {
    try await self.createBillingAccount(request: request, options: .init())
  }

  public func createBillingAccount(
    request: CreateBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createBillingAccount(
    billingAccount: BillingAccount?,
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    let request = CreateBillingAccountRequest().with {
      $0.billingAccount = billingAccount
    }
    return try await self.createBillingAccount(request: request)
  }

  public func createBillingAccount(
    billingAccount: BillingAccount?,
    parent: Swift.String,
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    let request = CreateBillingAccountRequest().with {
      $0.billingAccount = billingAccount
      $0.parent = parent
    }
    return try await self.createBillingAccount(request: request)
  }

  public func listProjectBillingInfo(request: ListProjectBillingInfoRequest) async throws
    -> GoogleCloudBillingV1.ListProjectBillingInfoResponse
  {
    try await self.listProjectBillingInfo(request: request, options: .init())
  }

  public func listProjectBillingInfo(
    request: ListProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ListProjectBillingInfoResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listProjectBillingInfo(
    byItem: ListProjectBillingInfoRequest
  ) -> any AsyncSequence<ProjectBillingInfo, Swift.Error> {
    self.listProjectBillingInfo(byItem: byItem, options: .init())
  }

  /// Lists the projects associated with a billing account. The current
  /// authenticated user must have the `billing.resourceAssociations.list` IAM
  /// permission, which is often given to billing account
  /// [viewers](https://cloud.google.com/billing/docs/how-to/billing-access).
  ///
  /// @Snippet(path: "CloudBilling_ListProjectBillingInfo")
  public func listProjectBillingInfo(
    byItem: ListProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ProjectBillingInfo, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBillingV1.ListProjectBillingInfoResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProjectBillingInfo(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProjectBillingInfo(
    name: Swift.String,
  ) -> any AsyncSequence<ProjectBillingInfo, Swift.Error> {
    let request = ListProjectBillingInfoRequest().with {
      $0.name = name
    }
    return self.listProjectBillingInfo(byItem: request)
  }

  public func getProjectBillingInfo(request: GetProjectBillingInfoRequest) async throws
    -> GoogleCloudBillingV1.ProjectBillingInfo
  {
    try await self.getProjectBillingInfo(request: request, options: .init())
  }

  public func getProjectBillingInfo(
    request: GetProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getProjectBillingInfo(
    name: Swift.String,
  ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo {
    let request = GetProjectBillingInfoRequest().with {
      $0.name = name
    }
    return try await self.getProjectBillingInfo(request: request)
  }

  public func updateProjectBillingInfo(request: UpdateProjectBillingInfoRequest) async throws
    -> GoogleCloudBillingV1.ProjectBillingInfo
  {
    try await self.updateProjectBillingInfo(request: request, options: .init())
  }

  public func updateProjectBillingInfo(
    request: UpdateProjectBillingInfoRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateProjectBillingInfo(
    name: Swift.String,
    projectBillingInfo: ProjectBillingInfo?,
  ) async throws -> GoogleCloudBillingV1.ProjectBillingInfo {
    let request = UpdateProjectBillingInfoRequest().with {
      $0.name = name
      $0.projectBillingInfo = projectBillingInfo
    }
    return try await self.updateProjectBillingInfo(request: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.GetIamPolicyRequest().with {
      $0.resource = resource
    }
    return try await self.getIamPolicy(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setIamPolicy(request: request)
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(
    resource: Swift.String,
    permissions: [Swift.String],
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    let request = GoogleIAMV1.TestIamPermissionsRequest().with {
      $0.resource = resource
      $0.permissions = permissions
    }
    return try await self.testIamPermissions(request: request)
  }

  public func moveBillingAccount(request: MoveBillingAccountRequest) async throws
    -> GoogleCloudBillingV1.BillingAccount
  {
    try await self.moveBillingAccount(request: request, options: .init())
  }

  public func moveBillingAccount(
    request: MoveBillingAccountRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBillingV1.BillingAccount {
    throw GoogleGax.RequestError.unimplemented
  }
}
