// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for `ListBillingAccounts`.
public struct ListBillingAccountsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Requested page size. The maximum page size is 100; this is also the
  /// default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying a page of results to return. This should be a
  /// `next_page_token` value returned from a previous `ListBillingAccounts`
  /// call. If unspecified, the first page of results is returned.
  public var pageToken: Swift.String = Swift.String()

  /// Options for how to filter the returned billing accounts.
  /// This only supports filtering for
  /// [subaccounts](https://cloud.google.com/billing/docs/concepts) under a
  /// single provided parent billing account.
  /// (for example,
  /// `master_billing_account=billingAccounts/012345-678901-ABCDEF`).
  /// Boolean algebra and other fields are not currently supported.
  public var filter: Swift.String = Swift.String()

  /// Optional. The parent resource to list billing accounts from.
  /// Format:
  ///   - `organizations/{organization_id}`, for example,
  ///     `organizations/12345678`
  ///   - `billingAccounts/{billing_account_id}`, for example,
  ///     `billingAccounts/012345-567890-ABCDEF`
  public var parent: Swift.String = Swift.String()

  /// Initialize a new instance of `ListBillingAccountsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBillingAccountsRequest().with { $0.pageSize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.ListBillingAccountsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
