// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents the pricing information for a SKU at a single point of time.
public struct PricingInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The timestamp from which this pricing was effective within the requested
  /// time range. This is guaranteed to be greater than or equal to the
  /// start_time field in the request and less than the end_time field in the
  /// request. If a time range was not specified in the request this field will
  /// be equivalent to a time within the last 12 hours, indicating the latest
  /// pricing info.
  public var effectiveTime: GoogleCloudWKT.Timestamp? = nil

  /// An optional human readable summary of the pricing information, has a
  /// maximum length of 256 characters.
  public var summary: Swift.String = Swift.String()

  /// Expresses the pricing formula. See `PricingExpression` for an example.
  public var pricingExpression: PricingExpression? = nil

  /// Aggregation Info. This can be left unspecified if the pricing expression
  /// doesn't require aggregation.
  public var aggregationInfo: AggregationInfo? = nil

  /// Conversion rate used for currency conversion, from USD to the currency
  /// specified in the request. This includes any surcharge collected for billing
  /// in non USD currency. If a currency is not specified in the request this
  /// defaults to 1.0.
  /// Example: USD * currency_conversion_rate = JPY
  public var currencyConversionRate: Swift.Double = Swift.Double()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `PricingInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PricingInfo().with { $0.effectiveTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let effectiveTime = CodingKeys(stringValue: "effectiveTime")
    static let summary = CodingKeys(stringValue: "summary")
    static let pricingExpression = CodingKeys(stringValue: "pricingExpression")
    static let aggregationInfo = CodingKeys(stringValue: "aggregationInfo")
    static let currencyConversionRate = CodingKeys(stringValue: "currencyConversionRate")

    static let _knownKeys: Set<Swift.String> = [
      "effectiveTime",
      "summary",
      "pricingExpression",
      "aggregationInfo",
      "currencyConversionRate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.effectiveTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .effectiveTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .summary) {
      self.summary = value
    }
    self.pricingExpression = try container.decodeIfPresent(
      PricingExpression.self, forKey: .pricingExpression)
    self.aggregationInfo = try container.decodeIfPresent(
      AggregationInfo.self, forKey: .aggregationInfo)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .currencyConversionRate)
    {
      self.currencyConversionRate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.effectiveTime, forKey: .effectiveTime)
    try container.encode(self.summary, forKey: .summary)
    try container.encodeIfPresent(self.pricingExpression, forKey: .pricingExpression)
    try container.encodeIfPresent(self.aggregationInfo, forKey: .aggregationInfo)
    try container.encode(self.currencyConversionRate, forKey: .currencyConversionRate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.PricingInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
