// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// Expresses a mathematical pricing formula. For Example:-
///
/// `usage_unit: GBy`
/// `tiered_rates:`
///    `[start_usage_amount: 20, unit_price: $10]`
///    `[start_usage_amount: 100, unit_price: $5]`
///
/// The above expresses a pricing formula where the first 20GB is free, the
/// next 80GB is priced at $10 per GB followed by $5 per GB for additional
/// usage.
public struct PricingExpression: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The short hand for unit of usage this pricing is specified in.
  /// Example: usage_unit of "GiBy" means that usage is specified in "Gibi Byte".
  public var usageUnit: Swift.String = Swift.String()

  /// The recommended quantity of units for displaying pricing info. When
  /// displaying pricing info it is recommended to display:
  /// (unit_price * display_quantity) per display_quantity usage_unit.
  /// This field does not affect the pricing formula and is for display purposes
  /// only.
  /// Example: If the unit_price is "0.0001 USD", the usage_unit is "GB" and
  /// the display_quantity is "1000" then the recommended way of displaying the
  /// pricing info is "0.10 USD per 1000 GB"
  public var displayQuantity: Swift.Double = Swift.Double()

  /// The list of tiered rates for this pricing. The total cost is computed by
  /// applying each of the tiered rates on usage. This repeated list is sorted
  /// by ascending order of start_usage_amount.
  public var tieredRates: [PricingExpression.TierRate] = []

  /// The unit of usage in human readable form.
  /// Example: "gibi byte".
  public var usageUnitDescription: Swift.String = Swift.String()

  /// The base unit for the SKU which is the unit used in usage exports.
  /// Example: "By"
  public var baseUnit: Swift.String = Swift.String()

  /// The base unit in human readable form.
  /// Example: "byte".
  public var baseUnitDescription: Swift.String = Swift.String()

  /// Conversion factor for converting from price per usage_unit to price per
  /// base_unit, and start_usage_amount to start_usage_amount in base_unit.
  /// unit_price / base_unit_conversion_factor = price per base_unit.
  /// start_usage_amount * base_unit_conversion_factor = start_usage_amount in
  /// base_unit.
  public var baseUnitConversionFactor: Swift.Double = Swift.Double()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PricingExpression`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PricingExpression().with { $0.usageUnit = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let usageUnit = CodingKeys(stringValue: "usageUnit")
    static let displayQuantity = CodingKeys(stringValue: "displayQuantity")
    static let tieredRates = CodingKeys(stringValue: "tieredRates")
    static let usageUnitDescription = CodingKeys(stringValue: "usageUnitDescription")
    static let baseUnit = CodingKeys(stringValue: "baseUnit")
    static let baseUnitDescription = CodingKeys(stringValue: "baseUnitDescription")
    static let baseUnitConversionFactor = CodingKeys(stringValue: "baseUnitConversionFactor")

    static let _knownKeys: Set<Swift.String> = [
      "usageUnit",
      "displayQuantity",
      "tieredRates",
      "usageUnitDescription",
      "baseUnit",
      "baseUnitDescription",
      "baseUnitConversionFactor",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .usageUnit) {
      self.usageUnit = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .displayQuantity) {
      self.displayQuantity = value
    }
    if let value = try container.decodeIfPresent(
      [PricingExpression.TierRate].self, forKey: .tieredRates)
    {
      self.tieredRates = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .usageUnitDescription) {
      self.usageUnitDescription = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .baseUnit) {
      self.baseUnit = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .baseUnitDescription) {
      self.baseUnitDescription = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .baseUnitConversionFactor)
    {
      self.baseUnitConversionFactor = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.usageUnit, forKey: .usageUnit)
    try container.encode(self.displayQuantity, forKey: .displayQuantity)
    try container.encode(self.tieredRates, forKey: .tieredRates)
    try container.encode(self.usageUnitDescription, forKey: .usageUnitDescription)
    try container.encode(self.baseUnit, forKey: .baseUnit)
    try container.encode(self.baseUnitDescription, forKey: .baseUnitDescription)
    try container.encode(self.baseUnitConversionFactor, forKey: .baseUnitConversionFactor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The price rate indicating starting usage and its corresponding price.
  public struct TierRate: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Usage is priced at this rate only after this amount.
    /// Example: start_usage_amount of 10 indicates that the usage will be priced
    /// at the unit_price after the first 10 usage_units.
    public var startUsageAmount: Swift.Double = Swift.Double()

    /// The price per unit of usage.
    /// Example: unit_price of amount $10 indicates that each unit will cost $10.
    public var unitPrice: GoogleType.Money? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TierRate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TierRate().with { $0.startUsageAmount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startUsageAmount = CodingKeys(stringValue: "startUsageAmount")
      static let unitPrice = CodingKeys(stringValue: "unitPrice")

      static let _knownKeys: Set<Swift.String> = [
        "startUsageAmount",
        "unitPrice",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .startUsageAmount) {
        self.startUsageAmount = value
      }
      self.unitPrice = try container.decodeIfPresent(GoogleType.Money.self, forKey: .unitPrice)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.startUsageAmount, forKey: .startUsageAmount)
      try container.encodeIfPresent(self.unitPrice, forKey: .unitPrice)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.billing.v1.PricingExpression.TierRate"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.PricingExpression"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
