// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Encapsulates a single SKU in Google Cloud
public struct Sku: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name for the SKU.
  /// Example: "services/6F81-5844-456A/skus/D041-B8A1-6E0B"
  public var name: Swift.String = Swift.String()

  /// The identifier for the SKU.
  /// Example: "D041-B8A1-6E0B"
  public var skuId: Swift.String = Swift.String()

  /// A human readable description of the SKU, has a maximum length of 256
  /// characters.
  public var description: Swift.String = Swift.String()

  /// The category hierarchy of this SKU, purely for organizational purpose.
  public var category: Category? = nil

  /// List of service regions this SKU is offered at.
  /// Example: "asia-east1"
  /// Service regions can be found at https://cloud.google.com/about/locations/
  public var serviceRegions: [Swift.String] = []

  /// A timeline of pricing info for this SKU in chronological order.
  public var pricingInfo: [PricingInfo] = []

  /// Identifies the service provider.
  /// This is 'Google' for first party services in Google Cloud Platform.
  public var serviceProviderName: Swift.String = Swift.String()

  /// The geographic taxonomy for this sku.
  public var geoTaxonomy: GeoTaxonomy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Sku`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Sku().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let skuId = CodingKeys(stringValue: "skuId")
    static let description = CodingKeys(stringValue: "description")
    static let category = CodingKeys(stringValue: "category")
    static let serviceRegions = CodingKeys(stringValue: "serviceRegions")
    static let pricingInfo = CodingKeys(stringValue: "pricingInfo")
    static let serviceProviderName = CodingKeys(stringValue: "serviceProviderName")
    static let geoTaxonomy = CodingKeys(stringValue: "geoTaxonomy")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "skuId",
      "description",
      "category",
      "serviceRegions",
      "pricingInfo",
      "serviceProviderName",
      "geoTaxonomy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .skuId) {
      self.skuId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.category = try container.decodeIfPresent(Category.self, forKey: .category)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .serviceRegions) {
      self.serviceRegions = value
    }
    if let value = try container.decodeIfPresent([PricingInfo].self, forKey: .pricingInfo) {
      self.pricingInfo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceProviderName) {
      self.serviceProviderName = value
    }
    self.geoTaxonomy = try container.decodeIfPresent(GeoTaxonomy.self, forKey: .geoTaxonomy)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.skuId, forKey: .skuId)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.category, forKey: .category)
    try container.encode(self.serviceRegions, forKey: .serviceRegions)
    try container.encode(self.pricingInfo, forKey: .pricingInfo)
    try container.encode(self.serviceProviderName, forKey: .serviceProviderName)
    try container.encodeIfPresent(self.geoTaxonomy, forKey: .geoTaxonomy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.Sku"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
