// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Encapsulates a single SKU in Google Cloud
public struct Sku: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name for the SKU.
  /// Example: "services/6F81-5844-456A/skus/D041-B8A1-6E0B"
  public var name: Swift.String = Swift.String()

  /// The identifier for the SKU.
  /// Example: "D041-B8A1-6E0B"
  public var skuId: Swift.String = Swift.String()

  /// A human readable description of the SKU, has a maximum length of 256
  /// characters.
  public var description: Swift.String = Swift.String()

  /// The category hierarchy of this SKU, purely for organizational purpose.
  public var category: Category? = nil

  /// List of service regions this SKU is offered at.
  /// Example: "asia-east1"
  /// Service regions can be found at https://cloud.google.com/about/locations/
  public var serviceRegions: [Swift.String] = []

  /// A timeline of pricing info for this SKU in chronological order.
  public var pricingInfo: [PricingInfo] = []

  /// Identifies the service provider.
  /// This is 'Google' for first party services in Google Cloud Platform.
  public var serviceProviderName: Swift.String = Swift.String()

  /// The geographic taxonomy for this sku.
  public var geoTaxonomy: GeoTaxonomy? = nil

  /// Initialize a new instance of `Sku`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Sku().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.v1.Sku"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
